apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgre-deployment
    labels:
      name: db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      type: PostgreDB
  template:
      metadata: 
        name: postgre-pod
        labels:
          type: PostgreDB
      spec:
        volumes:
          - name: postgres-storage
            persistentVolumeClaim:
              claimName: database-persistent-volume-claim
        containers:
            - name: postgre
              image: postgres
              ports:
                - containerPort: 5432
              volumeMounts:
                - name: postgres-storage
                  mountPath: /var/lib/postgresql/data
                  subPath: postgres
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: pgpassword
                      key: PGPASSWORD

