apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deployemnt
    labels:
      redis: isRedisTrue
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: redis-mem-db
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-mem-db
    spec:
      containers:
        - name: redis
          image: redis
          ports: 
              - containerPort: 6379
