apiVersion: apps/v1
kind: Deployment
metadata:
    name: worker-deployment
    labels:
      name: worker-deployment
spec:
    replicas: 1 
    selector:
      matchLabels:
        type: worker
    template:
      metadata:
        name: worker-pod
        labels:
          type: worker
      spec: 
        containers:
          - name: worker
            image: stephengrider/multi-worker
            env:
              - name: REDIS_HOST
                value: redis-cluster-ip
              - name: REDIS_PORT
                value: "6379"

